### PR TITLE
Add mass hotfix example script

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by ataylorme** [comment]
@uberhacker and @sean-e-dietrich do you think it would be useful to also show an example that updated a contrib module/WordPress plugin for a hotfix rather than an upstream update?

**Comment by uberhacker** [comment]
@ataylorme: Sure, that would be great to add.  If you could provide examples of both Drupal contrib and WordPress plugin updates, that would be awesome.

**Comment by uberhacker** [comment]
You could take this a step further and integrate the script into the plugin as a command.  It would require converting from bash to php, but it shouldn't be terribly difficult.

**Comment by ataylorme** [comment]
> You could take this a step further and integrate the script into the plugin as a command. It would require converting from bash to php, but it shouldn't be terribly difficult.

My thought here is that with most hotfixes QA should be part of the process, which is why the commands for creating a hotfix environment and deploying it are separate. 

In order to bypass the QA and go directly to deployment, I think there needs to be a Drupalgeddon type scenario. The vulnerability may be in a single module or plugin, in which case another script could update that specific item.

If there was one command that could be used to update all contrib modules or WordPress plugins on sites and deploy directly to live I feel it would be abused. 

For example, I don't want is folks using an uber command to update all WordPress plugins and hotfix deploying them directly to live outside of an emergency situation.

Example bash scripts still have the potential for abuse but cause some friction as the scripts need to be edited before they are run.

In a Drupalgeddon scenario, which has historically been a minimal occurrence, editing and running a Bash script is still a lot better than the current process and the friction of editing the bash script is far outweighed by the convenience it provides.

**Comment by sean-e-dietrich** [comment]
I am oddly just seeing this message. 

> If there was one command that could be used to update all contrib modules or WordPress plugins on sites and deploy directly to live I feel it would be abused.

Agree with this, because I would most certainly do that sometimes.

to answer your question though @ataylorme I believe that it would be useful to show any examples. They are usually helpful and sometimes people learn and ask questions at that point of, "I wonder if this is possible.."

**Comment by ataylorme** [comment]
Thanks for the feedback @sean-e-dietrich and @uberhacker. I added [an example script for mass hotfixing specific WordPress plugin updates](https://github.com/terminus-plugin-project/terminus-hotfix-plugin/blob/8fb17a496d17fd7a89a121ef24e95abcca0f3bd1/examples/mass-hotfix/terminus-mass-hotfix-wordpress-plugin-update.sh)

It works well _except_ it only runs on the first site from `org:site:list` in the `while` loop and then quits and I can't figure out why. I'm stepping away from it for a bit to clear my head but maybe you guys can catch something I missed.

**Comment by uberhacker** [comment]
@ataylorme: I think the issue is the list of sites returned is linefeed terminated.  What happens if try this?
```
PANTHEON_SITE_LIST="$(terminus org:site:list -n $PANTHEON_ORG_NAME --format=string --field=Name --tag=hotfix | xargs)"
```

**Comment by ataylorme** [comment]
`PANTHEON_SITE_LIST="$(terminus org:site:list -n $PANTHEON_ORG_NAME --format=string --field=Name --tag=hotfix | xargs)"`

No change. If I take all of my logic out and just do an echo inside the `while` loop it works just fine. Maybe something is returning an exit code that `set -ex` picks up on

**Comment by ataylorme** [comment]
> Maybe something is returning an exit code that `set -ex` picks up on

Nope, commenting out `set -ex` does not help either

**Comment by uberhacker** [comment]
What happens if you do this?
```
- while read -r SITE_NAME; do
+ for SITE_NAME in $PANTHEON_SITE_LIST; do
- done <<< "$PANTHEON_SITE_LIST"
+ done
```

**Comment by ataylorme** [comment]
That worked like a charm, thanks @uberhacker!

**Pull request merged**
